# Server
server.port=8080

# Application
spring.application.name=delivery-system

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/kafka-demo
spring.datasource.username=postgres
spring.datasource.password=postgres

# JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (useful for development)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false